apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: recommender-dr
spec:
  host: recommender
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommender-vs
spec:
  hosts:
  - recommender
  http:
  - fault:
      delay:
        percentage:
          value: 50.0
        fixedDelay: 5s
    route:
    - destination:
        host: recommender
        subset: v1
        port:
          number: 80